### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by anliski** [xvixvi/kiilto#1]
_Ladattu: 5.2.2016 klo 17.16_

**Yleisesti:**
-Siistiä koodia jokaisessa luokassa.
-Ohjelma jaettu loogisiin paketteihin ja paketit nimetty selkeästi.
-Luokat huolehtivat kukin omasta asiastaan ilman päällekkäisyyksiä, myös luokat nimetty selkeästi.
-Metoditkin on ohjeidenmukaisesti nimetty, ja jokainen tekee vain yhden asian.

**Kasakokoelma:**
-Kommentointi selkeytti hyvin toimintoja.

**Testit**
-Kaikki testit menivät läpi. (Pöytätestejä varten piti luonnollisesti hieman muokata aputiedoston osoitetta pöytä luokassa.)

**Muuta**
-En väkisinkään löydä mitään parannettavaa/kritisoitavaa koodista.

**Comment by vihaton** [comment]
**Kiitoksia kannustavasta palautteesta!** Helpottavaa kuulla, että joku muukin pystyy saamaan selvää tuosta koodista :+1:
