### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by organize** [xvixvi/kiilto#2]
<h2> Yleistä </h2>

<i>Ladattu: 15:34 - 19.02.2016</i>
- Hyvin paketoitu. Tosin aputiedostot kannattaa siirtää lähdekoodille suunnatun kansion ulkopuolelle.
- Hyvin sisennetty, helposti luettavaa (joitain luokkia lukuunottamatta).
- Testit erittäin kattavia.
- Bonuspisteet `toString`in toteuttamisesta hyvin.
- Luokkien järjestykset loogisia: muttujat, konstruktorit, metodit.

<h2> logiikka.* </h2>

<h4> Pelaaja </h4>
- Yleisesti, jos luokka toteuttaa rajapinnan, tulisi sen tyypiksi asettaa rajapinta, eikä implementaatio. (kts. [tämä](https://en.wikipedia.org/wiki/Liskov_substitution_principle) ja [tämä](https://en.wikipedia.org/wiki/Dependency_inversion_principle))
- Vaikkei luokkamuuttujan luominen konstruktorin ulkopuolella vaikuta mihinkään, olisi silti järkevintä joko luoda kaikki konstruktorin sisällä tai sen ulkopuolella.
- Nimeämiset ovat selkeitä ja koodi luettavaa.
- `liikaaKarkkeja` voitaisiin tiivistää yhteen riviin: `return karkit.getKarkkienMaara() > 10;` Sama metodiin `voittaja`. 
- Joissain metodikutsuissa metodin nimi trivialisoituu muuttujan tyypin vuoksi. esim. `omaisuus.getOmaisuudestaTulevatBonusKarkit();`: tässä tapauksessa `omaisuus.getBonusKarkit()` olisi ehkä kuvaavampi nimi. 
- `getHintaOmaisuustulotHuomioituna`: äärettömän helposti luettavaa, nimeämiset toteutettu erittäin hyvin.
- `onkoVaraa`: vaikeasti luettavaa. Muuttujat tulisi nimetä siten, ettei metodi tarvitse rivien väliin apukommentteja. 
- Metodi `getVaraus`: täydellinen metodi [Optional](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html)-luokan käyttämiseen.

<h4> Pelivelho </h4>
- `TUI` = ? (TextUI? edit: confirmed, suosittelen uudelleennimeämistä)
- `this`-viittaukset vain 1) konstruktorissa, 2) jos parametri tai lähimuuttuja saman niminen kun luokkamuuttuja tai 3) viitataan itse luokkaan (esim. parametreissä).
- Oletettavasti tekstin tulostus on `TUI`n tehtävä, joten metodin `pelaaKierros`/`pelaaVuoro` tulisi delegoida printtaukset sinne.
- Sisennykset osittain kateissa, mutta luokka onkin selvästi testikäytössä.

<h4> Poyta </h4>
- `"/home/xvixvi/kiilto/kiilto/src/main/java/aputiedostoja/omistustentiedot.csv"` on huono tapa viitata ulkoiseen tiedostoon. Se toimisi vain itselläsi, mutta oletan että koodi on väliaikaisratkaisu.
- `luoOmistukset` on melko kryptinen. Mikä on `j`?

<h3> Valineluokat </h3>
- `return;` Kasakokoelman konstruktorissa.
- Satunnaiset `this` viittaukset: joskus viittaat oikein, joskus et ollenkaan (esim. Merkkihenkilon konstruktori).
- `this("homo", ov, 3);` + 1
- Sisennys ja nimeämiset edelleen hyvää. Koodi on ymmärrettävää ja siistiä.

<h3> Omaisuusluokat </h3>
- Suunnittelussa outo epäsäännöllisyys: joissain metodeissa testaat, että parametri on raja-arvojen sisällä, kun taas toisissa teet suoria kutsuja ilman tarkistuksia. Ajattelen, että joko tarkistat raja-arvoja turhaan sillä koodi ilmeisesti ei koskaan anna vääriä syötteitä, tai tiettyihin metodeihin tarkistukset on unohdettu laittaa.
  - `siirraOmistus` ja `poistaOmistus`
- `getNakyvaOmistus`: [Optional](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html)

<h2> ui.* </h2>
- `selvitaPelaajienMaara`: älä käytä exceptioneita näin. Kutsu vaikka `continue` ja aseta `pm` rajojen tarkistusten jälkeen.
- `tarkistaKarrkienNostamisSyote` kannattaa uudelleenmiettiä. Saisit esim. tiivistettyä kaiken `throw new`-copypasten yhteen.
- Kaikenkaikkiaan projekti ei sisällä mitään vakavia virheitä tai mystiikkaa, lähinnä mikroskooppisia outouksia ja muita häröyksiä. Suunnitteludokumentista oli avuksi ja yleinen dokumentointi oli jokseenkin kattavaa, vaikkakin jossain metodeissa sitä olisi kaivattu.

**Comment by vihaton** [comment]
<h2>Kiitos organize!</h2>

Palautteesi oli yksityiskohtaista, kattavaa ja _rakentavaakin_ kaiken hyvän lisäksi! Koin, että siitä oli aidosti hyötyä jatkoa ajatellen.

Muutamat asiat ehdin jo korjaamaankin, mutta muutama jäi toistaiseksi työn alle. En esimerkiksi millään saa `Poyta` -luokan juuren kautta menevää polkua `/home/...` lyhennettyä, en sitten millään. Kaikenlaista inputStreamiä, polkua ja nimeä tuli koitettua... Osaisitko vinkata mistä yrittää löytää vastausta seuraavaksi? Sain `aputiedostoja`-kansion sentään vähän järkevämpään paikkaan, lähemmäksi juurta `/src/` -kansioon.

Vinkkisi **Optional** -luokan käyttämisestä oli hyvä, tosin taidan jättää sen opettelun hieman myöhäisemmäksi kun tuo käyttöliittymä pitäisi saada kuntoon.

**Comment by organize** [comment]
Kansioilla leikkiminen on ihan painajainen Javassa, syystä tai toisesta. 

Tällä hetkellä oma ratkaisu on näin:
`String path = getClass().getResource("/resources/path/to/filename.file").toExternalForm();`
tai vaihtoehtoisesti, jos haluat itse tiedoston:
`File file = new File(getClass().getResource("/resources/path/to/filename.file").getFile());`
jossa resources on `target/classes/`-kansiossa. 

Huomioitavaa: jos siis siirrät kansion ja rakenteesi on `target/classes/aputiedostoja`, tämä kansio tulee poistumaan jokaisella "Clean & Build"-suorituskerralla. Eli älä säikähdä jos projekti hajoaa käsiin yllättäen, siirrät kansion takaisin ja status quo palautuu!

**Comment by vihaton** [comment]
Kiitoksia! :+1:
